# site
title: Äggie Lee Pak Yee
baseurl: ""
url: "itchyeggie.com"
favicon: "/assets/images/ico.png"

# bio
header: Äggie Lee Pak Yee
desc: >
      李 柏 誼 <br>
      [Lei5 Paak3 Ji6]

# posts
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title